// src/sending-props-100-components-down-once/vue/src/components/RootComponent.vue
<template>
    <div>
        <button id="button" @click="onClick">Click me</button>
        <NestedComponent :counter="100" :value="value" />
    </div>
</template>
  
  <script>
  import NestedComponent from './NestedComponent.vue';
  
  export default {
    components: {
      NestedComponent
    },
    data() {
      return {
        value: 0
      };
    },
    methods: {
      onClick() {
        this.value += 1;
      }
    }
  };
  </script>

// src/react/sending-props-100-components-down/src/components/RootComponent.jsx
import React, { useState } from 'react';
import NestedComponent from './NestedComponent';

export default function RootComponent() {
    const [value, setValue] = useState(0);

    const on_click = () => {
        setValue(1);
    };

    return (
        <div>
            <button id="button" onClick={on_click}>Click me</button>
            <NestedComponent counter={100} value={value} />
        </div>
    );
}
