// src/replacing-whole-100-components-deep-subtree/vue/src/components/RootComponent.vue
<template>
    <div>
        <button id="button" @click="onClick">Click me</button>
        <NestedComponent1 v-if="value % 2 == 0" :counter="100" />
        <NestedComponent2 v-else :counter="100" />
    </div>
</template>
  
  <script>
  import NestedComponent1 from './NestedComponent1.vue';
  import NestedComponent2 from './NestedComponent2.vue';
  
  export default {
    components: {
      NestedComponent1,
      NestedComponent2
    },
    data() {
      return {
        value: 0
      };
    },
    methods: {
      onClick() {
        this.value += 1;
      }
    }
  };
  </script>

// src/replacing-whole-100-componentes-deep-subtree/react/src/components/RootComponent.jsx
import React, { useState } from 'react';
import NestedComponent1 from './NestedComponent1';
import NestedComponent2 from './NestedComponent2';

export default function RootComponent() {
    const [value, setValue] = useState(0);

    const on_click = () => {
        setValue(value + 1);
    };

    return (
        <div>
            <button id="button" onClick={on_click}>Click me</button>
            if (value % 2 === 0) {
                <NestedComponent1 counter={100} />
            } else {
                <NestedComponent2 counter={100} />
            }
        </div>
    );
}
