// src/for-adding-to-the-end/vue/src/components/ForComponent.vue
<template>
    <button id="button" @click="onClick">Click me</button>
    <div
      v-for="index in value"
      :key="index"
    > {{ index }} </div>
</template>

<script>

export default {
  data() {
    return {
      value: 0,
    };
  },
  methods: {
    onClick() {
      this.value++;
    }
  }
};
</script>

// src/for-adding-to-the-end/react/src/components/ForComponent.jsx
import React, { useState } from 'react';

export default function ForComponent() {
    const [value, setValue] = useState(0);

    const on_click = () => {
        setValue(value + 1);
    };

    return (
        <>
            <button id="button" onClick={on_click}>Click me</button>
            {Array.from({ length: value }).map((_, index) => (
                <div>
                    {index}
                </div>
            ))}
        </>
    );
}
