// src/updating-attributes-of-100-children-at-once/vue/src/components/ParentComponent.vue
<template>
  <div>
    <button id="button" @click="onClick">Click me</button>
    <ChildComponent
      v-for="index in 100"
      :key="index"
      :value="value"
    ></ChildComponent>
  </div>
</template>

<script>
import ChildComponent from './ChildComponent.vue';

export default {
  components: {
    ChildComponent
  },
  data() {
    return {
      value: 0,
    };
  },
  methods: {
    onClick() {
      this.value++;
    }
  }
};
</script>

// src/updating-self-and-sending-the-same-props-to-100-children/react/src/components/ParentComponent.jsx
import React, { useState } from 'react';
import ChildComponent from './ChildComponent';

export default function ParentComponent() {
    const [value, setValue] = useState(0);

    const on_click = () => {
        setValue(value + 1);
    };

    return (
        <>
            <div>
                <p>{value}</p>
            </div>
            <button id="button" onClick={on_click}>Click me</button>
            {Array.from({ length: 100 }).map((_, __) => (
                <ChildComponent value={0} />
            ))}
        </>
    );
}
