// src/sending-callback-through-100-components-up/react/src/components/NestedComponent.jsx
import React from 'react';

export default function NestedComponent({ depth, onButtonClick }) {
  const handleClick = () => {
    onButtonClick();
  };

  if (depth != 0) {
    return (
      <div>
        <NestedComponent depth={depth - 1} onButtonClick={onButtonClick} />
      </div>
    );
  } else {
    return <button onClick={handleClick}>Click me</button>;
  }
};

// src/sending-callback-through-100-components-up/vue/src/components/NestedComponent.vue
<template>
    <div v-if="depth != 0">
      <NestedComponent :depth="depth - 1" @button-clicked="handleButtonClick" />
    </div>
    <button v-else id="button" @click="handleButtonClick">Click me</button>
</template>

<script>
export default {
  name: 'NestedComponent',
  props: {
    depth: Number,
  },
  methods: {
    handleButtonClick() {
      this.$emit('button-clicked');
    },
  },
};
</script>
