// src/sending-callback-through-100-components-up/react/src/components/RootComponent.jsx
import React, { useState } from 'react';
import NestedComponent from './NestedComponent';

const RootComponent = () => {
  const [count, setCount] = useState(0);

  const handleButtonClick = () => {
    setCount(count + 1);
  };

  return (
    <div>
      <NestedComponent depth={100} onButtonClick={handleButtonClick} />
      <p>{count}</p>
    </div>
  );
};

export default RootComponent;

// src/sending-callback-through-100-components-up/vue/src/components/RootComponent.vue
<template>
  <div>
    <p>{{ count }}</p>
    <NestedComponent :depth="100" @button-clicked="handleButtonClick" />
  </div>
</template>

<script>
import NestedComponent from './NestedComponent.vue';

export default {
  name: 'RootComponent',
  components: {
    NestedComponent,
  },
  data() {
    return {
      count: 0,
    };
  },
  methods: {
    handleButtonClick() {
      this.count++;
    },
  },
};
</script>
