// src/replacing-whole-100-componentes-deep-subtree/angular/src/app/nested-component2/nested-component2.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-nested-component2',
  templateUrl: './nested-component2.component.html'
})
export class NestedComponent2Component {
  @Input() counter!: number;
}

Second version of nested component
<span *ngIf="counter !== 0">
  <app-nested-component2 [counter]="counter - 1"></app-nested-component2>
</span>

// src/replacing-whole-100-components-deep-subtree/react/src/components/NestedComponent2.jsx
import React from 'react';

export default function NestedComponent2({ counter }) {
    return (
        <>
            Second version of nested component
            { counter !== 0 ? (
                <span>
                    <NestedComponent2 counter={counter - 1} />
                </span>
            ) : null }
        </>
    );
}
